########################
# DJ-Raspi config file #
########################

secret_key: "change_me_20u4r9mrbpv39uw84gjbip9osr98jtafl3eijöakweg"

# Super user
admin_user: "admin"
admin_email: "admin@localhost"
admin_password: "password"

# Service host
listen: "0.0.0.0"
port: "8000"
allowed_hosts: "*"
